export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';

export const GET_RESTAURANTS_REQUEST = 'GET_RESTAURANTS_REQUEST';
export const CREATE_RESTAURANT_REQUEST = 'CREATE_RESTAURANT_REQUEST';
export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST';
export const DELETE_RESTAURANT_REQUEST = 'DELETE_RESTAURANT_REQUEST';
export const SET_RESTAURANT = 'SET_RESTAURANT';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
